### ISSUE TITLE
PostCSS Plugins Guidelines

### ISSUE THREAD

**Issue by ai** [devex-web-frontend/postcss-assets-rebase#2]
There are few [PostCSS Plugins Guidelines]()https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md violations:
- 4.4. Add `postcss-plugin` keyword to `package.json`.
- 4.3. Maintain a changelog.
- 3.2. Use result.warn for warnings.

/cc @cakeinpanic

**Comment by cakeinpanic** [comment]
@ai done!
