### ISSUE TITLE
webpack example

### ISSUE THREAD

**Issue by oojacoboo** [devex-web-frontend/postcss-assets-rebase#21]
Do you have an example of usage with webpack?  Updates to readme?

**Comment by cakeinpanic** [comment]
It can be used with webpack like any other postcss plugin
I've edited example from postss-loader (https://www.npmjs.com/package/postcss-loader)

```
module.exports = {
    module: {
        loaders: [
            {
                test:   /\.css$/,
                loader: "style-loader!css-loader!postcss-loader"
            }
        ]
    },
    postcss: function () {
        return {
            defaults:  [precss, autoprefixer, rebaser({assetsPath: "assets/imported", relative: true  })]
        };
    }
}
```

**Comment by oojacoboo** [comment]
Thanks and yep, I did something similar based on other plugins, just didn't see any examples of this and webpack is pretty common, so figured it be included in the readme.
